# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_experience/schema/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agent_experience/schema/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$agent_experience/schema/common.proto\x12\x13\x61gent_experience.v1\"\xc7\x02\n\nTypedValue\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x17\n\rinteger_value\x18\x02 \x01(\x12H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x17\n\rboolean_value\x18\x04 \x01(\x08H\x00\x12\x15\n\x0b\x62ytes_value\x18\x05 \x01(\x0cH\x00\x12\x34\n\nlist_value\x18\x06 \x01(\x0b\x32\x1e.agent_experience.v1.ListValueH\x00\x12\x32\n\tmap_value\x18\x07 \x01(\x0b\x32\x1d.agent_experience.v1.MapValueH\x00\x12\x38\n\treference\x18\x08 \x01(\x0b\x32#.agent_experience.v1.ValueReferenceH\x00\x12\x14\n\nnull_value\x18\t \x01(\x08H\x00\x42\x06\n\x04kind\"<\n\tListValue\x12/\n\x06values\x18\x01 \x03(\x0b\x32\x1f.agent_experience.v1.TypedValue\"\x95\x01\n\x08MapValue\x12\x39\n\x06\x66ields\x18\x01 \x03(\x0b\x32).agent_experience.v1.MapValue.FieldsEntry\x1aN\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.agent_experience.v1.TypedValue:\x02\x38\x01\"\xe2\x01\n\x0eValueReference\x12?\n\x04type\x18\x01 \x01(\x0e\x32\x31.agent_experience.v1.ValueReference.ReferenceType\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x16\n\x0esource_node_id\x18\x03 \x01(\t\"i\n\rReferenceType\x12\x1e\n\x1aREFERENCE_TYPE_UNSPECIFIED\x10\x00\x12\r\n\tRUN_INPUT\x10\x01\x12\x0f\n\x0bNODE_OUTPUT\x10\x02\x12\n\n\x06SECRET\x10\x03\x12\x0c\n\x08\x41RTIFACT\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_experience.schema.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPVALUE_FIELDSENTRY']._loaded_options = None
  _globals['_MAPVALUE_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_TYPEDVALUE']._serialized_start=62
  _globals['_TYPEDVALUE']._serialized_end=389
  _globals['_LISTVALUE']._serialized_start=391
  _globals['_LISTVALUE']._serialized_end=451
  _globals['_MAPVALUE']._serialized_start=454
  _globals['_MAPVALUE']._serialized_end=603
  _globals['_MAPVALUE_FIELDSENTRY']._serialized_start=525
  _globals['_MAPVALUE_FIELDSENTRY']._serialized_end=603
  _globals['_VALUEREFERENCE']._serialized_start=606
  _globals['_VALUEREFERENCE']._serialized_end=832
  _globals['_VALUEREFERENCE_REFERENCETYPE']._serialized_start=727
  _globals['_VALUEREFERENCE_REFERENCETYPE']._serialized_end=832
# @@protoc_insertion_point(module_scope)
