# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_experience/schema/package.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agent_experience/schema/package.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%agent_experience/schema/package.proto\x12\x13\x61gent_experience.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n\x0bPackageFile\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x0e\n\x06sha256\x18\x03 \x01(\x0c\"\x81\x03\n\x19\x45xperiencePackageManifest\x12\x1e\n\x16package_format_version\x18\x01 \x01(\r\x12\x12\n\npackage_id\x18\x02 \x01(\t\x12\x1c\n\x14source_repository_id\x18\x03 \x01(\t\x12/\n\x0b\x65xported_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tpublisher\x18\x05 \x01(\t\x12\x14\n\x0crevision_ids\x18\x06 \x03(\t\x12/\n\x05\x66iles\x18\x07 \x03(\x0b\x32 .agent_experience.v1.PackageFile\x12\x1a\n\x12\x65mbedding_provider\x18\x08 \x01(\t\x12\x17\n\x0f\x65mbedding_model\x18\t \x01(\t\x12\x1b\n\x13\x65mbedding_dimension\x18\n \x01(\r\x12\"\n\x1arequired_tool_contract_ids\x18\x0b \x03(\t\x12\x11\n\tsignature\x18\x0c \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_experience.schema.package_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKAGEFILE']._serialized_start=95
  _globals['_PACKAGEFILE']._serialized_end=152
  _globals['_EXPERIENCEPACKAGEMANIFEST']._serialized_start=155
  _globals['_EXPERIENCEPACKAGEMANIFEST']._serialized_end=540
# @@protoc_insertion_point(module_scope)
