# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_experience/schema/package.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agent_experience/schema/package.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%agent_experience/schema/package.proto\x12\x13\x61gent_experience.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n\x0bPackageFile\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x0e\n\x06sha256\x18\x03 \x01(\x0c\"\xa0\x01\n\x11PackageCapability\x12\x15\n\rcapability_id\x18\x01 \x01(\t\x12\x1a\n\x12version_constraint\x18\x02 \x01(\t\x12\x19\n\x11input_schema_hash\x18\x03 \x01(\x0c\x12\x1a\n\x12output_schema_hash\x18\x04 \x01(\x0c\x12\x10\n\x08optional\x18\x05 \x01(\x08\x12\x0f\n\x07\x61liases\x18\x06 \x03(\t\"\xfc\x05\n\x19\x45xperiencePackageManifest\x12\x1e\n\x16package_format_version\x18\x01 \x01(\r\x12\x12\n\npackage_id\x18\x02 \x01(\t\x12\x1c\n\x14source_repository_id\x18\x03 \x01(\t\x12/\n\x0b\x65xported_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tpublisher\x18\x05 \x01(\t\x12\x14\n\x0crevision_ids\x18\x06 \x03(\t\x12/\n\x05\x66iles\x18\x07 \x03(\x0b\x32 .agent_experience.v1.PackageFile\x12\x1a\n\x12\x65mbedding_provider\x18\x08 \x01(\t\x12\x17\n\x0f\x65mbedding_model\x18\t \x01(\t\x12\x1b\n\x13\x65mbedding_dimension\x18\n \x01(\r\x12\"\n\x1arequired_tool_contract_ids\x18\x0b \x03(\t\x12\x11\n\tsignature\x18\x0c \x01(\x0c\x12\x14\n\x0cpackage_name\x18\r \x01(\t\x12\x17\n\x0fpackage_version\x18\x0e \x01(\t\x12!\n\x19\x61gent_experience_requires\x18\x0f \x01(\t\x12\x17\n\x0fpython_requires\x18\x10 \x01(\t\x12\x1b\n\x13required_frameworks\x18\x11 \x03(\t\x12\x45\n\x15required_capabilities\x18\x12 \x03(\x0b\x32&.agent_experience.v1.PackageCapability\x12\x1b\n\x13signature_algorithm\x18\x13 \x01(\t\x12\x16\n\x0esigning_key_id\x18\x14 \x01(\t\x12\x1a\n\x12signing_public_key\x18\x15 \x01(\x0c\x12\x16\n\x0epackage_digest\x18\x16 \x01(\x0c\x12\x1e\n\x16supersedes_package_ids\x18\x17 \x03(\t\x12!\n\x19\x65xperience_schema_version\x18\x18 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_experience.schema.package_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKAGEFILE']._serialized_start=95
  _globals['_PACKAGEFILE']._serialized_end=152
  _globals['_PACKAGECAPABILITY']._serialized_start=155
  _globals['_PACKAGECAPABILITY']._serialized_end=315
  _globals['_EXPERIENCEPACKAGEMANIFEST']._serialized_start=318
  _globals['_EXPERIENCEPACKAGEMANIFEST']._serialized_end=1082
# @@protoc_insertion_point(module_scope)
